language: go
go:
- 1.13.x
- 1.12.x
- 1.11.x
- 1.10.x
sudo: false
script:
- go test
before_deploy:
- mkdir -p release
- export GOOS=linux GOARCH=amd64; go build -o release/check-prometheusexporter-${GOOS}-${GOARCH}
- export GOOS=linux GOARCH=386; go build -o release/check-prometheusexporter-${GOOS}-${GOARCH}
- export GOOS=darwin GOARCH=amd64; go build -o release/check-prometheusexporter-${GOOS}-${GOARCH}
- export GOOS=windows GOARCH=amd64; go build -o release/check-prometheusexporter-${GOOS}-${GOARCH}
- export GOOS=windows GOARCH=386; go build -o release/check-prometheusexporter-${GOOS}-${GOARCH}
deploy:
  provider: releases
  api_key:
    secure: k1/N1cttTSMzrKqQIwb8e5qv5wFhV52yySXh8bCjov3fFeu6EFi9dlCee/H3PhvfMOioAfpsLIGWE1Gn/1GDH0cVv+mHF4UYHVmUR10HEjf9Jlo/+HuIkXV4r3rPHxmC3CCbf0RNlh2ufu/RNG8wRN1ju2JAeWFY5eROcxx45ALUXklq01qfwcMi3q+QVzbZUVKnVWokjw0A90ocjUMcKudkYoDXocEQw9KEb8LsWJK+OyBIBhuTx93W687QThZ84B8aKdWkoIrQM5KYdYLsMW/5z1UK2efoXc/v6IHccRMM01vx8QWCS/TxlEkE85QvtJvqi4Z+dHwvH28Pbfj/3N93BWLDcVzgMSCD01zwGjAwuSj9m5U3r0pNlG22souASxe1REg50Ouk3qhY/KR04uu6tvG1irwbL168zTy6Osq6o+ZgjOWiWbMdIBTo+MzhEmK7yjag/h23mJ003vgVelOhrpQ7Rj+zIMa7ed/BOTWQ0f/+bUXmCJIrjaxwUXqqczJJQeW6pfFLcj9N8/DKO27yfHcBAmcDMeLf0txlX88sZBmCii9Wc+GT3e+MsBc8Y/x8NDjoXySxqtKPpoIOG8vkQNBFhlBd7Zo5LFl5r8PfBXs07oKMgVbFqrBLnLePRPOa0Xcg3VXSC44mQeDe/aenwcT4NWvj3NV8/GNJih8=
  file: "*"
  on:
    repo: nxadm/check-prometheusexporter
