package main

import (
	"flag"
	"fmt"
	"os"
)

const usage = appname + ", " + version + ".\n" +
	`Nagios/Icinga check to query metric endpoint of Prometheus exporters.
Author: ` + author + `.
Repo: ` + repo + `.
   _       _       _       _       _       _       _       _
_-(_)-  _-(_)-  _-(_)-  _-(")-  _-(_)-  _-(_)-  _-(_)-  _-(_)-
*(___)  *(___)  *(___)  *%%%%%  *(___)  *(___)  *(___)  *(___)
// \\   // \\   // \\   // \\   // \\   // \\   // \\   // \\

Usage:
  ` + appname + `
    -u <URL> -s <metric> -d <metric>
    -w <seconds> -c <seconds>
    [-t <seconds>]
  ` + appname + ` -v
  ` + appname + ` -h

Options:
  -u <URL>       Prometheus probe endpoint.
  -s <metric>    Key of int metric for success (1) or failure (0).
  -d <duration>  Key of int metric with the duration of the check.
  -w <seconds>   Duration after which the check is marked as WARNING.
  -c <seconds>   Duration after which the check is marked as CRITICAL.
  -t <seconds>   Duration after which the check will time out (CRITICAL).
  -v             Show the version of this program.
  -h             Show this screen.

Example for Prometheus output generated by script_exporter
(https://github.com/adhocteam/script_exporter):
  ` + appname + ` -u http://somehost:9172/probe?name=probename \
    -s 'script_success{script="probename"}' \
    -d 'script_duration_seconds{script="probename"}' \
    -w 6 -c 8 -t 15

Include the escaping backslashes for the quotes.
`

func handleCLI() Config {
	help := flag.Bool("h", false, "")
	progVersion := flag.Bool("v", false, "")
	url := flag.String("u", "", "")
	successMetric := flag.String("s", "", "")
	durationMetric := flag.String("d", "", "")
	warningSec := flag.Int("w", 0, "")
	criticalSec := flag.Int("c", 0, "")
	timeoutSec := flag.Int("t", 0, "")

	flag.Usage = func() { fmt.Println(usage) }
	flag.Parse()

	// Handle early exits
	switch {
	case *help:
		fmt.Println(usage)
		os.Exit(UNKNOWN)
	case *progVersion:
		fmt.Println(appname + ", " + version + ".")
		os.Exit(UNKNOWN)
	case *url == "" || *successMetric == "" || *durationMetric == "" ||
		*warningSec == 0 || *criticalSec == 0 || *timeoutSec == 0:
		fmt.Println("[UNKNOWN] Invalid of missing values for parameters.")
		os.Exit(UNKNOWN)
	}

	// Import the values
	cfg := Config{}
	cfg.Url = *url
	cfg.SuccessMetric = *successMetric
	cfg.DurationMetric = *durationMetric
	cfg.WarningSec = *warningSec
	cfg.CriticalSec = *criticalSec
	cfg.TimeoutSec = *timeoutSec

	return cfg
}
