---
name: ci
on: [push, pull_request]
jobs:
  build:
    env:
      CGO_ENABLED: 1
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test
        run: go test -race -v -timeout 2m ./...
      - name: Build cmd UNIX
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p $GITHUB_WORKSPACE/packages/
          PROG_VERSION=$(git describe --tags --match 'v[0-9]*')
          OS=$(echo ${{ matrix.os }} | cut -d'-' -f1)
          go build -ldflags "-w -s -X main.version=$PROG_VERSION" -o $GITHUB_WORKSPACE/packages/check-prometheusexporter-${OS}-amd64
          ls -lh $GITHUB_WORKSPACE/packages/check-prometheusexporter-*
      - name: Build cmd Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p D:\a\check-prometheusexporter\check-prometheusexporter\packages\
          $progVersion = git describe --tags --match 'v[0-9]*' | Out-String
          go build -ldflags "-w -s -X main.version=$progVersion" -o D:\a\check-prometheusexporter\check-prometheusexporter\packages\check-prometheusexporter-windows-amd64.exe
          dir D:\a\check-prometheusexporter\check-prometheusexporter\packages\check-prometheusexporter-*
      - name: Archive packages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            ${{ github.workspace }}/packages/*
            D:\a\check-prometheusexporter\check-prometheusexporter\packages\*.exe
          if-no-files-found: error
  release-to-github:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Download packages
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: Upload to Github Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/*"
          draft: true
          body: "New build."
