---
name: ci
on: [push, pull_request]
jobs:
  build:
    env:
      CGO_ENABLED: 1
      OS: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.21.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Test
        run: go test -race -v -timeout 2m ./...
      - name: Build cmd
        run: |
          mkdir -p $GITHUB_WORKSPACE/packages/
          go build -ldflags "-w -s -X main.version=version" -o $GITHUB_WORKSPACE/packages/check-prometheusexporter-$OS
          ls -lh $GITHUB_WORKSPACE/packages
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          retention-days: 1
          path: ${{ github.workspace }}/packages/
  release-to-github:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nxadm' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: packages
      - name: Upload to Github Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "check-prometheusexporter-*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          body: "New build."
